config/routes.rb
Sepp::Application.routes.draw do
  root 'home#index'

  get "/home", to: "home#index"
  get "/transition", to: "opportunity#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/opportunity_controller.rb
class OpportunityController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opportunity_helper.rb
module OpportunityHelper
end

app/views/home/index.html.haml
%ul.curtains
  %li#home_top
    %a.curtain-links.curtain-links-active{href: '#home_top'}
    %section#home
      %h1#scroll_message Scroll Down To Hear Our Story
      .home-content
        %img{src: image_url('appletree1.png')}
      .about-office
        %p Apple Tree Dentistry is the home of happy patients! It is our priority to create a friendly and gentle environment while performing excellent oral health care. We understand, for many, going to the dentist can be scary and uncomfortable. We feel it is important to gain trust with our patients by delivering true and honest dentistry. We are focused on the mechanics of oral health care and maintain the importance of educating our patients about their mouth and over all wellness. Our staff cares about people, not just teeth.
        %p  Our services include routine cleanings, exams, radiographs, and oral screenings. We also do all restorative work such as composite fillings, amalgam fillings, crowns, bridges, inlays, onlays, partial dentures, and full dentures. We do refer out for some endodontic needs, orthodontics, oral surgery and implant cases. Dr. Sepp has a full lab in the office where he still enjoys the fabrication of appliances which eliminates the use of an out-of-office lab.
        %p In 2005, Dr. Sepp bought the property where the Lindley farmhouse stood and he renovated the house to meet current medical standards. Some of our patients can still remember visiting the office in their youth when it was an active farm. The coziness of “home” is something everyone feels upon entering and every room looks out to the acreage that provides great viewing of unexpected wildlife. Birds, squirrels, and deer make their visits routinely and the apple trees on the property can be enjoyed by all.
      .home-contact
        = fa_icon 'phone', text: '(503) 620-2185'
  %li#about_top
    %section#about
      .about-content-container
        %p Dr. Toivo T Sepp graduated from Tufts University in Boston, Massachusetts and soon after moved to Oregon where he and his wife raised their family. Dr. Sepp has been providing superb dentistry in the Tigard area for more than 30 years and has established lasting relationships with people in all walks of life. He sees every person he meets as a chance to learn something new and to make a positive impact. Dr. Sepp loves life and always has. He enjoys music of all kinds, people of all kinds, and gets joy out of helping others. One of his passions is building things and fixing things that need it, which is why his way of dentistry is focused on the mechanics of the mouth first. "People eventually will get tired of paying for glitz and glam. Yes, it is important to look swell, but if your mouth is not working properly, then what good will cosmetics do?"
      .doc-image
        %img{src: image_url('doc.jpg')}

  %li#contact_top
    %section#contact
      .map-panel
        %a#show_map{href: '#'}
          = fa_icon 'map-marker', text: 'Toggle Map'
        #map.hidden{:style => "width: 100%; height: 250px;"}
      .details
        %address#contact_info.pull-left
          %strong Appletree Dentistry
          %br
          %span
            16035 SW Pacific Hwy
          %br
          %span
            Tigard, OR 97224
          %br
          = fa_icon 'phone', text: '(503) 620-2185'
          %br
          = fa_icon 'envelope'
          = mail_to 'drsepp@frontier.com'
        .hours.pull-left
          %table.table.table-hover
            %thead
              %tr
                %th.hours_header Day
                %th.hours_header Time
            %tbody
              %tr
                %td Monday
                %td 8:00 AM - 5:00 PM
              %tr
                %td Tuesday
                %td 8:00 AM - 5:00 PM
              %tr
                %td Wednesday
                %td 8:00 AM - 5:00 PM
              %tr
                %td Thursday
                %td 8:00 AM - 5:00 PM
              %tr
                %td Friday
                %td 8:00 AM - 4:00 PM

app/views/layouts/_header.html.haml
%nav.navbar.navbar-fixed-top.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#nav-items", 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a{href: '/'}
        #logo.pull-left
          Dr.Toivo Sepp, DMD
        .nav-header
          = link_to "https://www.facebook.com/pages/Apple-Tree-Dentistry/381465318532295", {target: '_blank'} do
            = fa_icon 'facebook-square', text: 'Find Us On ', right: true
    .collapse.navbar-collapse#nav-items.navbar-right
      %ul.nav.navbar-nav
        %li
          %a#home_scroll.page-scroll{:href => '/'} Home
        %li
          %a#about_scroll.page-scroll{:href => '#about_top'} About
        %li
          %a#contact_scroll.page-scroll{:href => '#contact_top'} Contact
        %li
          = link_to("Transition", transition_path, class: 'nav-item transition')
        %li#social_link
          = link_to "https://www.facebook.com/pages/Apple-Tree-Dentistry/381465318532295", {target: '_blank'} do
            = fa_icon 'facebook-square'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %title Dr. Toivo Sepp, DMD
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag :modernizr
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
    - flash.each do |name, msg|
      = content_tag :div, msg, class: name
    = render :partial => "layouts/header"
    = yield

app/views/opportunity/index.html.haml
%br
.back-button
  = link_to home_path do
    = fa_icon 'arrow-left', text: 'Back'
%h1#transition_header Appletree Dentistry
%hr
.row
  %h1.text-center.bold Dental Office For Lease
  .building-info.col-lg-8.col-lg-offset-1
    %h3 Building Info
    %table.table.table-hover
      %thead
        %tr
          %th Level
          %th Square Ft.
          %th Features
      %tbody
        %tr
          %td Main
          %td 1,564
          %td Five large operatories, full laboratory, sterilization room, patient restroom, spacious waiting and reception area.
        %tr
          %td Top
          %td 672
          %td Private office with restroom.
        %tr
          %td Lower
          %td 621
          %td Break room with staff bath and laundry facilities.
        %tr#total
          %td Total
          %td 2,857
          %td
.row
  .features.col-lg-8.col-lg-offset-1
    %h3 Features
    %blockquote
      %ul#features
        %li
          %p
            2,857 total square feet of office space on 4.3 acres (building for lease, property not for sale).
        %li
          %p Landscape view from every room.
        %li
          %p Five-year old equipment provided by Beaverstate Dental in Newberg, Oregon.
        %li
          %p Office is fully equipped.
.row
  .photos.col-lg-8.col-lg-offset-1
    #carousel-generic.carousel.slide{"data-ride" => "carousel"}
      %ol.carousel-indicators
        %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
        %li{"data-slide-to" => "1", "data-target" => "#carousel-generic"}
        %li{"data-slide-to" => "2", "data-target" => "#carousel-generic"}
        %li{"data-slide-to" => "3", "data-target" => "#carousel-generic"}
        %li{"data-slide-to" => "4", "data-target" => "#carousel-generic"}
        %li{"data-slide-to" => "5", "data-target" => "#carousel-generic"}
        %li{"data-slide-to" => "6", "data-target" => "#carousel-generic"}
      .carousel-inner
        .item.active
          %img{:src => image_url('home.jpg')}/
          .carousel-caption
            %h3 Front view of office
        .item
          %img{:src => image_url('about2.jpg')}/
          .carousel-caption
            %h3 Patient waiting area
        .item
          %img{:src => image_url('about.jpg')}/
          .carousel-caption
            %h3 Reception area
        .item
          %img{:src => image_url('inside2.jpg')}/
          .carousel-caption
            %h3 Waiting area
        .item
          %img{:src => image_url('chair.jpg')}/
          .carousel-caption
            %h3 One of five spacious operatories
        .item.vertical
          %img{:src => image_url('contact.jpg')}/
          .carousel-caption
            %h3 Old barn still on property
        .item.vertical
          %img{:src => image_url('barn.jpg')}/
          .carousel-caption
            %h3 1930's barn is seen on property
      %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left
      %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right
.row
  .contact-for-purchase.col-lg-8.col-lg-offset-1
    %h3 Contact:
    %h3
      = fa_icon 'phone', text: '503-620-2185'
    %h3
      = fa_icon 'envelope'
      = mail_to 'drsepp@frontier.com'